from tkinter import *
m=Tk()
m.geometry("450x300")
m.title("Student record")
name_var=StringVar()
ht_var=StringVar()
year_var=StringVar()
branch_var=StringVar()
spec_var=StringVar()
cgpa_var=StringVar()
marks_var=StringVar()
def submit():
    h = Label(w)
    name = name_var.get()
    ht = ht_var.get()
    year = year_var.get()
    branch = branch_var.get()
    spec = spec_var.get()
    cgpa= cgpa_var.get()
    marks = marks_var.get()
    if name!="" and ht!="" and year!="" and branch!="" and spec!="" and cgpa!="" and marks!="":
        h.config(text=f"name: {name}\nht: {ht}\nyear: {year}\nbranch: {branch}\nspec: {spec}\ncgpa: {cgpa}\nmarks: {marks}\n")
    else:
        h.config(text=f"no")
    name_var.set("")
    ht_var.set("")
    year_var.set("")
    branch_var.set("")
    spec_var.set("")
    cgpa_var.set("")
    marks_var.set("")
l1 = Label(m, text = "name")
l2 = Label(m, text = "ht")
l3 = Label(m, text = "year")
l4 = Label(m, text = "branch")
l5 = Label(m, text = "spec")
l6 = Label(m, text = "cgpa")
l7 = Label(m, text = "marks")
t1 = Entry(m,width = 30, textvariable = name_var)
t2 = Entry(m, width = 30, textvariable = ht_var)
t3 = Entry(m,width = 30, textvariable = year_var)
t4 = Entry(m, width = 30, textvariable = branch_var)
t5 = Entry(m,width = 30, textvariable = spec_var)
t6 = Entry(m, width = 30, textvariable = cgpa_var)
t7 = Entry(m,width = 30, textvariable = marks_var)
b1 = Button(m, text = "Submit", command = submit)
l1.place(x = 40,y=60)
t1.place(x = 110,y =60)
l2.place(x = 40,y=100)
t2.place(x = 110, y=100)
l3.place(x = 40,y=100)
t3.place(x = 110,y =60)
l4.place(x = 40,y=100)
t4.place(x = 110, y=100)
l5.place(x = 40,y=60)
t5.place(x = 110,y = 60)
l6.place(x = 40,y=100)
t6.place(x = 110, y=100)
l7.place(x = 40,y=100)
t7.place(x = 110, y=100)
b1.place(x = 40,y=130)

m.mainloop()


    
    
    