f_ref = open("paragraph.txt","w")
f_ref.write("Every Sunset has a story to tell and a colour of ending the day but the hope for the beginning the next day and tells us every day should end no matter what memories it holds.")
f_ref = open("paragraph.txt","r")
paragraph = f_ref.read()
print("Original paragraph:")
print(paragraph)
paragraph = paragraph.replace("a", "b")
paragraph = paragraph.replace("e", "f")
paragraph = paragraph.replace("i", "j")
paragraph = paragraph.replace("o", "p")
paragraph = paragraph.replace("u", "v")
print("after replacing para is")
print(paragraph)
f_ref.close()